# =====================
# Configuración exclusiva del perfil 'dev'
# =====================

# Consola H2 habilitada solo en desarrollo
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL verbose en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
